### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stromvirvel**
Add information how to backup a database

### CODE REVIEW

**Comment by mitar** [comment]
Thanks!

**Comment by mitar** [comment]
BTW, why is not simply mounting `/var/lib/postgresql` mount point outside and then regularly backuping it at the file level enough?

**Comment by stromvirvel** [comment]
You could do that, but if you copy these files during load (e.g. transaction is running), the copied data could be corrupt / non-consistent. The other thing is that you cannot simply restore a database on a db server where other databases already exist. Additionally, a filesystem backup could be incompatible with other postgresql versions.

You could turn off your application and copy consistent data - but a dump via pg_dump works online.

There's a possibility to freeze your container with "docker pause", take a snapshot of the underyling filesystem (LVM, zfs), unfreeze your container and backup the snapshot. I'd recommend this kind of backup if you're running a application which stores data on a filesystem (e.g. pictures) and on a database seamlessly, and you should take care backing up filesystem and database at the same time.

There are different ways, depending on your needs. We could explain this topic in the README, but I think a dump should work in the most cases.

**Comment by mitar** [comment]
> You could do that, but if you copy these files during load (e.g. transaction is running), the copied data could be corrupt / non-consistent.

I mean, the whole point of databases is that you can turn them off at any time and data is consistent.

> Additionally, a filesystem backup could be incompatible with other postgresql versions.

True, but that's why you have a Docker image. :-) You spawn a container, mount the backup in, and you are ready to go. I think in world before Docker containers all this might be tricky. But now it is easy to temporary create a new database instance and link it to backup files.

> We could explain this topic in the README, but I think a dump should work in the most cases.

I think it is good as an example. No need to put these questions into README. I was just curious for myself. :-)

**Pull request merged**
